C   19/11/83 406051717  MEMBER NAME  CHFREQ   (S)           FORTRAN
      SUBROUTINE CHFREQ(NFREQ,SFREQ,DFREQ,KFREQ,FREQ)
C
C
C=====ROUTINE TO MODIFY THE (5,7) DRIFT SPACE MATRIX ELEMENTS TO
C=====TAKE ACCOUNT OF R.F. FREQUENCY SHIFTS.
C
C
C
      IMPLICIT REAL*8(A-H,O-Z)
C
#include "clatic.for"
C
C=====GET NEXT FREQUENCY SHIFT
      IF(NFREQ.EQ.0)FREQ=0.
      IF(NFREQ.EQ.0)RETURN
      FREQ=SFREQ+DFREQ*KFREQ
C
C
C
C=====LOOP OVER THE TYPE LIST
C
      DO 10 I=1,NTYPE
      IF(ID(I).NE.1)GO TO 10
      TMAT(5,7,I)=-XX(I)*FREQ
   10 CONTINUE
C
C
      RETURN
      END
