C   19/11/83 406051716  MEMBER NAME  CHKICK   (S)           FORTRAN
      SUBROUTINE CHKICK
C
C
C=====ROUTINE TO MODIFY THE MATRIX ELEMENTS OF KICKER MAGNETS ACCORDING
C=====TO A NEW RANDOM DISTRIBUTION WITH THE SAME R.M.S. KICKER STRENGTHS
C=====SO THAT THE RANGE OF THE EFFECTS CAUSED BY DIFFERENT CLOSED ORBITS
C=====CAN BE ESTIMATED.
C
      IMPLICIT REAL*8(A-H,O-Z)
C
#include "clatic.for"
#include "cnlist.for"
C
C
C
C
      NKICK=(KICK/10)*10
      IKICK=KICK-NKICK
C
C
C
C
C=====LOOP OVER THE TYPE LIST OVERWRITING THE KICKER FIELDS.
C
      DO 10 I=1,NTYPE
      IF(ID(I).NE.6.AND.ID(I).NE.7)GO TO 10
      CALL RANNOR(GAUS1,GAUS2)
      XX(I)=3.0E-5*GAUS2*SCLKIK
      IFL=ID(I)-5
      GO TO (21,22),IFL
   21 TMAT(2,6,I)= XX(I)
      TMAT(5,1,I)=-XX(I)
      TMAT(2,7,I)=-XX(I)
      GO TO 10
   22 TMAT(4,6,I)=-XX(I)
      TMAT(5,3,I)= XX(I)
      TMAT(4,7,I)= XX(I)
   10 CONTINUE
C
C
      RETURN
      END
