C   25/07/82 406051701  MEMBER NAME  ROQUAD   (S)           FORTRAN
      SUBROUTINE ROQUAD(NTY)
C=====GENERATES MATRICES FOR ARBITRARILY ROTATED QUADS.
C=====EACH I/P QUADSLICE OF TYPE=11 IS SPLIT INTO A QUAD/SKEWQUAD PAIR
C=====AND AN ADDITIONAL MEMBER IS ADDED TO THE TYPE LIST.
C=====THE S/SQ PAIR WILL BE LATER USED IS A ZERO LENGTH Q-D-SQ TRIPLET.
C=====THERE IS THUS NO NEED TO CHANGE THE LENGTHS (YY) OR THE NUMBER OF
C=====OF SLICES (NUNT).
C=====THE     QUAD STRENGTH IS A=XX*COS(2*PHI)
C=====THE ANTIQUAD STRENGTH IS B=XX*SIN(2*PHI)
C=====SQRT(A**2+B**2)=XX-----SO THAT THE TOTAL STRENGTH IS NOT CHANGED.
C=====IN THE TYPE LIST THE QUAD IS PUT FIRST,THE SKEWQUAD SECOND.BUT
C=====BOTH ARE GIVEN THE SAME NAME! (E.G. RA1).THEIR TYPES ARE HOWEVER
C=====DIFFERENT NAMELY 3 & 4
C=====AFTER GENERATING THE EXTRA QUADS MARK THESE MAGNET TYPE PAIRS WITH
C=====A LARGE CRAZY ANGLE.IN THE LATTICE LIST WE USE THE SAME NAME--RA1.
C=====THE LOGIC THEN SEARCHES THE TYPE LIST & FINDS THE QUAD & CREATES
C=====Q-D-SQ TRIPLETS--GETTING THE SKEWQUAD DATA FROM THE NEXT
C=====POSITION IN THE TYPE LIST.SO EVERYTHING IS ANCHORED TO THE QUAD!
C
      IMPLICIT REAL*8 (A-H,O-Z)
      CHARACTER *8 NSAV 
C
C
      INCLUDE "clatic.for"
      INCLUDE "csol.for"
C
C
C
      YYSAV=YY(NTY)
      XXSAV=XX(NTY)
      NSAV=NAME(NTY)
      NUSAV=NUNT(NTY)
      NSOLSV=NSOL(NTY)
      A=XXSAV*DCOS(2.*TWIST(NTY))
      B=XXSAV*DSIN(2.*TWIST(NTY))
C
C=====GENERATE QUAD PARAMETERS
      TMAT(2,1,NTY)=-A
      TMAT(4,3,NTY)=A
      XX(NTY)=A
      YY(NTY)=YYSAV
      ID(NTY)=3
      NAME(NTY)=NSAV
      TWIST(NTY)=99.
      NTWIST(NTY)=99
      NUNT(NTY)=NUSAV
      NSOL(NTY)=NSOLSV
      NTY=NTY+1
C
C=====GENERATE SKEW-QUAD PARAMETERS
      TMAT(2,3,NTY)=-B
      TMAT(4,1,NTY)=-B
      XX(NTY)=B
      YY(NTY)=YYSAV
      ID(NTY)=4
      NAME(NTY)=NSAV
      TWIST(NTY)=99.
      NTWIST(NTY)=99
      NUNT(NTY)=NUSAV
      NSOL(NTY)=NSOLSV
      RETURN
      END
