      SUBROUTINE G05KFF(GENID, SUBID, SEED, LSEED, STATE, LSTATE, IFAIL)
      INTEGER GENID, SUBID, SEED(LSEED), LSEED, STATE(LSTATE), LSTATE
      INTEGER IFAIL
      CALL init_generator (2)
      CALL SET_INITIAL_SEED(SEED(1), SEED(1))

      END SUBROUTINE G05KFF
