C   19/05/82 205251503  MEMBER NAME  GEOM     (MAY92.S)     FORTRAN
C
C
C
C
C                 MAIN ROUTINE FOR RUNNING SLICK
C                 -----------------------------
C         MODIFIED AND  CALLED  GEOM TO INVESTIGATE ROTATOR GEOMETRY.
C        'THICK SLICE' VERSION WITH EXACT MATRICES FOR THICK
C         CONTIGUOUS SLICES SO THAT INTEGRALS CAN BE HANDLED.
C
C         FAST VERSION USING SHORT CUTS FOR DRIFT SPACES.
C
C
C   NTYPE=(NUMBER OF DIFFERENT MAGNET-TYPES) <= 1000
C   WARNING ==> WHEN CHANGING NO. OF TYPES, TRANS1 MUST BE CHANGED
C   BEAM-LINE MUST CONTAIN ALL ELEMENTS IN STORAGE RING.
C   2 <= (TOTAL NUMBER OF ELEMENTS IN THE BEAM-LINE) <= (NO. IN CLOORB)
C
C
C   EACH MAGNET-TYPE IS SPECIFIED BY (ID,NAME,XX,YY ------).
C   ID=  ( 1 , 2 , 3 ,    4   , 5 ,   6    ,   7    ,  8 , 9 ,  10)
C   MEANS(DRF,BBX,QUA,SKEW-QUA,CAV,HOR-KICK,VER-KICK,SEXT,BBY,SOLENOID)
C   ID=  (11         ,12           ,13           )
C   MEANS(ROTAT.QUAD  FOC.HOR.BEND  FOC.VERT.BEND)
C
C
C   (ID .EQ. 99) DEFINES HALF SUPERPERIOD IN THE UNPERTURBED MACHINE.
C   NINS=(NUMBER OF HALF SUPERPERIODS IN THE BEAM-LINE).
C   (ID .NE. 1,2,3,9) ARE TREATED AS PERTURBATIONS.
C
C
C   FOR THICK LENS VERSION INPUT(!!!) STRENGTHS XX ARE:
C   XX=(ELEMENT STRENGTH). FOR DIFFERENT ID NUMBERS, XX ARE GIVEN BY:
C      (L, L*BY/BRHO, L*(DBY/DX)/BRHO, L*(DBY/DY)/BRHO,
C     V*COS(PHIS)*H/(R*E0),L*BY/BRHO,L*BX/BRHO,L*(D**2*BY/DX**2)/BRHO,
C     L*BX/BRHO,L*BZ/BRHO)
C   YY=0 ---- IF ID=1,5,99.
C     =(ELEMENT LENGTH) ---- OTHERWISE.
C
C
C
C   T(J,K,I)=(JK-TH ELEMENT OF THE TRANSFORMATION MATRIX FOR
C     THE I-TH MAGNET-TYPE) ---- THIN-LENS ASSUMED.
C
C
C
C   FOR MEANING OF INPUT FLAG SETTINGS (IN NAMELIST) SEE SUBROUTINE
C   LATTIN.
C
C   THE 7-DIMENSIONAL VECTOR IS (X,X',Y,Y',DL,DE/E,1).
C   THE FIRST AND LAST BEAM-LINE ELEMENTS MUST BE DRIFTS WITH XX=0.
C
C
C
C
      IMPLICIT REAL*8(A-H,O-Z)
C
C
C
#include "cloorb.for"
#include "cnlist.for"
#include "clatic.for"
#include "csol.for"
C
C
C
C
      PI=3.1415926535897932D0
C
C
C
C
C
C
C
C
      CALL ROT100(0.D0,0,0)
      CALL LATTIN(RLENGE,IROT,ICOUP)
C
C
C
C
C
C
C
C
C     ***************************************************************
C     *  LOOP OVER THE ENERGY STEPS    (OR TAKE ONE ENERGY STEP AND *
C     *  ---------------------------    LOOP OVER FREQUENCY STEPS.) *
C     *                                                             *
C     *  1)CALCULATE ROTATOR GEOMETRY IN ROTGEOM.                   *
C     *                                                             *
C     ***************************************************************
C
C
C
C
C
C
      ISTEP=NSTEP
C
C
      DO 50 IE0=1,ISTEP
      E0=E00+(IE0-1)*DE0
      IF(IVROT.EQ.0)GO TO 611
C=====CHANGE ROTATOR SETTINGS AT EACH ENERGY.
      CALL ROT100(E0,0,1)
      DO 622 I=1,NTYPE
      IID=ID(I)
      IF(IID.EQ.2.OR.IID.EQ.9)CALL ROT100(E0,I,2)
      IF(IID.EQ.2)CALL DIPH(XX(I),YY(I),TMAT(1,1,I))
      IF(IID.EQ.9)CALL DIPV(XX(I),YY(I),TMAT(1,1,I))
  622 CONTINUE
  611 CONTINUE
C
C
      WRITE(6,100)E0,IE0
  100 FORMAT(' ',F17.5,I10,2F17.5)
      CALL RTGEOM(E0,IE0)
C
C
C
   50 CONTINUE
C
C
      STOP
C
C
 1060 WRITE(6,1061) NREM
 1061 FORMAT(' ','RUN TERMINATED WITH ',I5,' SECONDS LEFT')
 1062 FORMAT(' ','TIME REMAINING:     ',I5,' SECONDS ')
      STOP
C
C
C
C
C
C
      END
