C   06/05/84 401171754  MEMBER NAME  HEDGE    (MAY92.S)     FORTRAN
      SUBROUTINE HEDGE(X,YY,T,NU,TT21,TT43,NSOL)
C
C
C=====ROUTINE TO SET UP EDGE FIELDS OF HORIZONTAL DIPOLE OR CF.
C=====THESE WILL BE INSERTED INTO LATTICE AT FRONT AND BACK OF THE
C=====REAL DIPOLE.
C
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8 T(7,7)
      DATA ICALL/0/,GAP/0.05D0/

      INCLUDE "cnlist.for"

C
C
C
      T(2,1)=0.D0
      T(4,3)=0.D0
      TT21  =0.D0
      TT43  =0.D0
CC*   KILL EDGE FIELDS.
      IF(X.EQ.0.D0)RETURN
C=====TURN OFF EDGE FIELDS. Also set to DRIFT at two places in LATTIN. 
      IF(IEDGE.EQ.0)RETURN
C      IF(NSOL.NE.0)RETURN
C
C
C
C
C=====END FIELDS: AS IN SPINOR.
C=====CONSTRUCT EQUIVALENT QUADRUPOLE MATRIX.
C
      XX=X/YY
      B1=0.5D0*X*NU
      SINI=DSIN(B1)
      COSI=DCOS(B1)
      T1=SINI/COSI
      PSI=(1.+SINI**2)*GAP*XX/COSI
      T2=DSIN(B1-PSI)/DCOS(B1-PSI)
      T(2,1)= T1*XX
      T(4,3)=-T2*XX
      TT21  = T1*XX
      TT43  =-T2*XX
C     WRITE(53,200)X,XX,YY,B1,SINI,COSI,T1
C 200 FORMAT(' ',7D14.5)
C      IF(ICALL.EQ.0)WRITE(53,100)GAP,T(2,1),T(4,3)
      WRITE(53,100)GAP,T(2,1),T(4,3)
  100 FORMAT(' ','DIPOLE GAP SIZE (CM),MATRIX ELEMENTS:',F7.2,2E12.5)
      ICALL=ICALL+1
C
C
      RETURN
      END
