C   06/05/84 602092036  MEMBER NAME  THIQAD   (S)           FORTRAN
      SUBROUTINE THIQUAD(X,YY,IKICK,NTY,T,ECHROM)
C
C
C
C=====ROUTINE TO SET UP A 7X7 THICK NORMAL-QUAD MATRIX.
C
C
C
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE "csol.for"

      REAL*8 T(7,7)
C
      IF(YY.EQ.0.D0)RETURN

C=====REDEFINE THE STRENGTH 'X'
      X=X/(1.D0+ECHROM)
      XX=X/YY
C=====INITIALISE MATRICES
      T(1,2)=YY
      T(3,4)=YY
      IF(XX.EQ.0.D0)RETURN
C
C
C
C=====CONSTRUCT A THICK NORMAL-QUAD.
      RXX=DSQRT(DABS(XX))
      FQ1=0.D0
      FQ2=1.D0
      IF(XX.GT.0.D0)FQ1=1.D0
      IF(XX.GT.0.D0)FQ2=0.D0
      ARG=RXX*YY
      DC=DCOS(ARG)
      DS=DSIN(ARG)
      DCH=DCOSH(ARG)
      DSH=DSINH(ARG)
      T(1,1)= FQ1*DC     + FQ2*DCH
      T(2,2)= FQ1*DC     + FQ2*DCH
      T(1,2)= FQ1*DS/RXX + FQ2*DSH/RXX
      T(2,1)=-FQ1*DS*RXX + FQ2*DSH*RXX
      T(3,3)= FQ2*DC     + FQ1*DCH
      T(4,4)= FQ2*DC     + FQ1*DCH
      T(3,4)= FQ2*DS/RXX + FQ1*DSH/RXX
      T(4,3)=-FQ2*DS*RXX + FQ1*DSH*RXX
C
C
C=====QUAD.WITH ALIGNMENT ERRORS:NOTE THE SIGNS OF TMAT( ,7)
C=====APPROX. VERSION FOR NOW (24/7/84)
C     IF(IKICK.EQ.3.OR.IKICK.EQ.4)CALL RANNOR(GAUS1,GAUS2)
C     IF(IKICK.EQ.3)T(4,7)=-X*1.E-3*GAUS1*SCLKIK
C     IF(IKICK.EQ.4)T(2,7)=+X*1.E-3*GAUS1*SCLKIK
C     TWIST(NTY)=1.E-3*GAUS1*SCLKIK
C     NTWIST(NTY)=IKICK
C
C
C     WRITE(6,12)
C  12 FORMAT(///)
C     DO 11 I=1,7
C  11 WRITE(6,10)(T(I,J),J=1,7)
C  10 FORMAT(' ',7E14.7)
C
C
C
C
      RETURN
      END
